# Generated by Django 5.2 on 2025-09-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.TextField()),
                ('contact_type', models.CharField(choices=[('sms', 'SMS'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=50)),
                ('show_alerts', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'subscriber',
                'verbose_name_plural': 'subscribers',
            },
        ),
        migrations.DeleteModel(
            name='SubscriberModel',
        ),
    ]
