# Generated by Django 5.2 on 2025-09-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_subscriber_delete_subscribermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='contact',
            field=models.TextField(unique=True),
        ),
    ]
