# Generated by Django 5.2 on 2025-09-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='created_at',
        ),
        migrations.AddField(
            model_name='alert',
            name='detected_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
